package Client;

import java.io.File;
import java.net.InetAddress;
import java.net.UnknownHostException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Corinne
 */
public class JFrameClientSTF extends javax.swing.JFrame {

    private Client client;
    private File fichier;

    /**
     * Creates new form JFrameClientSTF
     */
    public JFrameClientSTF() {
        client = new Client();
        fichier = null;
        initComponents();
    }

    public void AffichageMSGInformation(int codeErreur) {
        switch (codeErreur) {
            case 0:
                JOptionPane.showMessageDialog(jDialogErreur,
                        "Le transfert s'est bien effectué !",
                        "Information : transfert de fichier",
                        JOptionPane.INFORMATION_MESSAGE);
                break;
            case 1:
                JOptionPane.showMessageDialog(jDialogErreur,
                        "Fichier '"+jTextFieldFichierDistant.getText()+"' est introuvable sur le serveur !",
                        "Erreur : transfert de fichier",
                        JOptionPane.WARNING_MESSAGE);
                break;
            case 2:
                JOptionPane.showMessageDialog(jDialogErreur,
                        "Violation de l'accès sur le serveur",
                        "Erreur : transfert de fichier",
                        JOptionPane.WARNING_MESSAGE);
                break;
            case 3:
                JOptionPane.showMessageDialog(jDialogErreur,
                        "Disque plein ou dépassement de l'espace alloué sur le serveur",
                        "Erreur : transfert de fichier",
                        JOptionPane.WARNING_MESSAGE);
                break;
            case 4:
                JOptionPane.showMessageDialog(jDialogErreur,
                        "Opération TFTP illégale",
                        "Erreur : transfert de fichier",
                        JOptionPane.WARNING_MESSAGE);
                break;
            case 5:
                JOptionPane.showMessageDialog(jDialogErreur,
                        "Transfert ID inconnu",
                        "Erreur : transfert de fichier",
                        JOptionPane.WARNING_MESSAGE);
                break;
            case 6:
                JOptionPane.showMessageDialog(jDialogErreur,
                        "Le fichier "+jTextFieldFichierDistant.getText()+" existe déjà sur le Serveur",
                        "Erreur : transfert de fichier",
                        JOptionPane.WARNING_MESSAGE);
                break;
            case 7:
                JOptionPane.showMessageDialog(jDialogErreur,
                        "Utilisateur inconnu",
                        "Erreur : transfert de fichier",
                        JOptionPane.WARNING_MESSAGE);
                break;
            case 8:
                JOptionPane.showMessageDialog(jDialogErreur,
                        "Fichier non trouvé ou violation de l'accès !",
                        "Erreur : transfert de fichier",
                        JOptionPane.WARNING_MESSAGE);
                break;
            case 9:
                JOptionPane.showMessageDialog(jDialogErreur,
                        "Impossible de lire le fichier (problème d'encodage)",
                        "Erreur : transfert de fichier",
                        JOptionPane.WARNING_MESSAGE);
                break;
            case 10:
                JOptionPane.showMessageDialog(jDialogErreur,
                        "Le serveur n'est pas joignable",
                        "Erreur : transfert de fichier",
                        JOptionPane.WARNING_MESSAGE);
                break;
            case 11:
                JOptionPane.showMessageDialog(jDialogErreur,
                        "Le nom du fichier local '"+jTextFieldFichierLocal.getText()+"' existe déjà !",
                        "Erreur : transfert de fichier",
                        JOptionPane.WARNING_MESSAGE);
                break;
            default:
                JOptionPane.showMessageDialog(jDialogErreur,
                        "Erreur non identifiée ! \n Verifiez si vous avez rentré des caractères spéciaux dans le nom d'un fichier.",
                        "Erreur : transfert de fichier",
                        JOptionPane.WARNING_MESSAGE);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser = new javax.swing.JFileChooser();
        jDialogErreur = new javax.swing.JDialog();
        jLabelTitre = new javax.swing.JLabel();
        jLabelAdresseServer = new javax.swing.JLabel();
        jTextFieldAdressServer = new javax.swing.JTextField();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelSendfile = new javax.swing.JPanel();
        jButtonSendfile = new javax.swing.JButton();
        jLabelNomFichier = new javax.swing.JLabel();
        jButtonSelect = new javax.swing.JButton();
        jLabelAddressFile = new javax.swing.JLabel();
        jPanelReceive = new javax.swing.JPanel();
        jButtonReceivefile = new javax.swing.JButton();
        jLabelFichierDistant = new javax.swing.JLabel();
        jLabelFichierLocal = new javax.swing.JLabel();
        jTextFieldFichierDistant = new javax.swing.JTextField();
        jTextFieldFichierLocal = new javax.swing.JTextField();
        jLabelCheminEnrg = new javax.swing.JLabel();
        jTextFieldCheminEnrg = new javax.swing.JTextField();
        jButtonSelectDossier = new javax.swing.JButton();

        jDialogErreur.setMinimumSize(new java.awt.Dimension(400, 150));
        jDialogErreur.setResizable(false);

        javax.swing.GroupLayout jDialogErreurLayout = new javax.swing.GroupLayout(jDialogErreur.getContentPane());
        jDialogErreur.getContentPane().setLayout(jDialogErreurLayout);
        jDialogErreurLayout.setHorizontalGroup(
            jDialogErreurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialogErreurLayout.setVerticalGroup(
            jDialogErreurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplication Client STF");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabelTitre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitre.setText("Client STF");
        jLabelTitre.setName("jLabelTitre"); // NOI18N

        jLabelAdresseServer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelAdresseServer.setText("Serveur :");
        jLabelAdresseServer.setName("jLabelAdresseServer"); // NOI18N

        jTextFieldAdressServer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldAdressServer.setToolTipText("");
        jTextFieldAdressServer.setName("jTextFieldAdressServer"); // NOI18N

        jTabbedPane.setToolTipText("");
        jTabbedPane.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jButtonSendfile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonSendfile.setText("Envoyer");
        jButtonSendfile.setToolTipText("");
        jButtonSendfile.setActionCommand("Envoyer");
        jButtonSendfile.setName("jButtonSendfile"); // NOI18N
        jButtonSendfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendFileActionPerformed(evt);
            }
        });

        jLabelNomFichier.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelNomFichier.setText("Chemin du fichier :");
        jLabelNomFichier.setName("jLabelNomFichier"); // NOI18N

        jButtonSelect.setText("Select.");
        jButtonSelect.setToolTipText("");
        jButtonSelect.setName("jButtonSelect"); // NOI18N
        jButtonSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectFileActionPerformed(evt);
            }
        });

        jLabelAddressFile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanelSendfileLayout = new javax.swing.GroupLayout(jPanelSendfile);
        jPanelSendfile.setLayout(jPanelSendfileLayout);
        jPanelSendfileLayout.setHorizontalGroup(
            jPanelSendfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSendfileLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelNomFichier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAddressFile, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSelect)
                .addGap(30, 30, 30))
            .addGroup(jPanelSendfileLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jButtonSendfile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSendfileLayout.setVerticalGroup(
            jPanelSendfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSendfileLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(jPanelSendfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomFichier, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSelect)
                    .addComponent(jLabelAddressFile, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jButtonSendfile)
                .addGap(22, 22, 22))
        );

        jTabbedPane.addTab("Envoyer un fichier", jPanelSendfile);

        jButtonReceivefile.setText("Recevoir");
        jButtonReceivefile.setActionCommand("Recevoir");
        jButtonReceivefile.setName("jButtonReceivefile"); // NOI18N
        jButtonReceivefile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceiveFileActionPerformed(evt);
            }
        });

        jLabelFichierDistant.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelFichierDistant.setText("Nom du fichier distant :");

        jLabelFichierLocal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelFichierLocal.setText("Nom du fichier local :");

        jLabelCheminEnrg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCheminEnrg.setText("Chemin d'enregistrement :");

        jTextFieldCheminEnrg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButtonSelectDossier.setText("Select.");
        jButtonSelectDossier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectDossierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelReceiveLayout = new javax.swing.GroupLayout(jPanelReceive);
        jPanelReceive.setLayout(jPanelReceiveLayout);
        jPanelReceiveLayout.setHorizontalGroup(
            jPanelReceiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReceiveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelReceiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFichierLocal)
                    .addComponent(jLabelCheminEnrg)
                    .addComponent(jLabelFichierDistant))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelReceiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldFichierDistant, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFichierLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCheminEnrg, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSelectDossier)
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReceiveLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonReceivefile)
                .addGap(186, 186, 186))
        );
        jPanelReceiveLayout.setVerticalGroup(
            jPanelReceiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReceiveLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelReceiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFichierDistant)
                    .addComponent(jTextFieldFichierDistant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelReceiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFichierLocal)
                    .addComponent(jTextFieldFichierLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelReceiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCheminEnrg, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCheminEnrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSelectDossier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButtonReceivefile)
                .addGap(25, 25, 25))
        );

        jLabelFichierDistant.getAccessibleContext().setAccessibleName("");

        jTabbedPane.addTab("Recevoir un fichier", jPanelReceive);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabelTitre)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabelAdresseServer)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldAdressServer, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelAdresseServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldAdressServer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SendFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendFileActionPerformed

        if (fichier != null && !jTextFieldAdressServer.getText().equals("")) {
            try {
                int crem;
                InetAddress AdressServeur = InetAddress.getByName(jTextFieldAdressServer.getText());
                crem = client.SendFile(fichier, AdressServeur);
                AffichageMSGInformation(crem);
            } catch (UnknownHostException ex) {
                JOptionPane.showMessageDialog(jDialogErreur,
                        "L'adresse du Serveur est inconnue.",
                        "Problème : Envoi de fichier",
                        JOptionPane.WARNING_MESSAGE);
            }

        } else {
            if (jTextFieldAdressServer.getText().equals("")) {
                JOptionPane.showMessageDialog(jDialogErreur,
                        "Vous n'avez pas indiqué l'adresse du Serveur.",
                        "Problème : Envoi de fichier",
                        JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(jDialogErreur,
                        "Vous n'avez pas selectionné de fichier.",
                        "Problème : Envoi de fichier",
                        JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_SendFileActionPerformed

    private void ReceiveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceiveFileActionPerformed
        if (!jTextFieldCheminEnrg.getText().equals("") && !jTextFieldAdressServer.getText().equals("") && !jTextFieldFichierDistant.getText().equals("") && !jTextFieldFichierLocal.getText().equals("")) {
            try {
                int crrv;
                InetAddress AdressServeur = InetAddress.getByName(jTextFieldAdressServer.getText());
                crrv = client.ReceiveFile(jTextFieldFichierLocal.getText(), jTextFieldFichierDistant.getText(), AdressServeur, jTextFieldCheminEnrg.getText());
                AffichageMSGInformation(crrv);
            } catch (UnknownHostException ex) {
                JOptionPane.showMessageDialog(jDialogErreur,
                        "L'adresse du Serveur est inconnue.",
                        "Problème : Envoi de fichier",
                        JOptionPane.WARNING_MESSAGE);
            }
        } else {
            if (jTextFieldAdressServer.getText().equals("")) {
                JOptionPane.showMessageDialog(jDialogErreur,
                        "Vous n'avez pas indiqué l'adresse du Serveur.",
                        "Problème : Envoi de fichier",
                        JOptionPane.WARNING_MESSAGE);
            } else {

                if (jTextFieldFichierDistant.getText().equals("")) {
                    JOptionPane.showMessageDialog(jDialogErreur,
                            "Vous n'avez pas indiqué le nom du fichier distant.",
                            "Problème : Envoi de fichier",
                            JOptionPane.WARNING_MESSAGE);
                } else {

                    if (jTextFieldFichierLocal.getText().equals("")) {
                        JOptionPane.showMessageDialog(jDialogErreur,
                                "Vous n'avez pas indiqué le nom du fichier local.",
                                "Problème : Envoi de fichier",
                                JOptionPane.WARNING_MESSAGE);
                    } else {

                        if (jTextFieldCheminEnrg.getText().equals("")) {
                            JOptionPane.showMessageDialog(jDialogErreur,
                                    "Vous n'avez pas selectionné l'endroit où vous voulez enregistrer le fichier.",
                                    "Problème : Envoi de fichier",
                                    JOptionPane.WARNING_MESSAGE);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_ReceiveFileActionPerformed

// Selection du fichier
    private void SelectFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectFileActionPerformed
        jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int returnVal = jFileChooser.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            //Recuperation du fichier
            fichier = jFileChooser.getSelectedFile();

            // Affichage du fichier selectionne
            jLabelAddressFile.setText(fichier.getAbsolutePath());
        } else {
            fichier = null;
            jLabelAddressFile.setText("");
        }
    }//GEN-LAST:event_SelectFileActionPerformed

    // Selection du dossier
    private void SelectDossierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectDossierActionPerformed
        jFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = jFileChooser.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            //Recuperation du dossier
            fichier = jFileChooser.getSelectedFile();

            // Affichage du dossier selectionne
            jTextFieldCheminEnrg.setText(fichier.getAbsolutePath());
        } else {
            fichier = null;
            jTextFieldCheminEnrg.setText("");
        }
    }//GEN-LAST:event_SelectDossierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameClientSTF.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameClientSTF.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameClientSTF.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameClientSTF.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrameClientSTF jf = new JFrameClientSTF();
                jf.setLocationRelativeTo(null);
                jf.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReceivefile;
    private javax.swing.JButton jButtonSelect;
    private javax.swing.JButton jButtonSelectDossier;
    private javax.swing.JButton jButtonSendfile;
    private javax.swing.JDialog jDialogErreur;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JLabel jLabelAddressFile;
    private javax.swing.JLabel jLabelAdresseServer;
    private javax.swing.JLabel jLabelCheminEnrg;
    private javax.swing.JLabel jLabelFichierDistant;
    private javax.swing.JLabel jLabelFichierLocal;
    private javax.swing.JLabel jLabelNomFichier;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JPanel jPanelReceive;
    private javax.swing.JPanel jPanelSendfile;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextField jTextFieldAdressServer;
    private javax.swing.JTextField jTextFieldCheminEnrg;
    private javax.swing.JTextField jTextFieldFichierDistant;
    private javax.swing.JTextField jTextFieldFichierLocal;
    // End of variables declaration//GEN-END:variables
}
